#!/bin/bash
# Install the FreeUp Space CLI wrapper without sudo.

set -u

SCRIPT_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
CLI_SCRIPT="$SCRIPT_DIR/scripts/freeup_space.py"
INSTALL_DIR="$HOME/.local/bin"
WRAPPER="$INSTALL_DIR/freeup-space"
MARKER="FreeUp Space wrapper generated by install.sh"

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 is required but was not found on PATH." >&2
    exit 1
fi

if [ ! -f "$CLI_SCRIPT" ]; then
    echo "ERROR: CLI script not found: $CLI_SCRIPT" >&2
    exit 1
fi

if [ "$(uname -s)" != "Darwin" ]; then
    echo "Warning: live disk audits require macOS. Installing the wrapper anyway for docs/tests/report generation."
fi

mkdir -p "$INSTALL_DIR" || exit 1

if [ -e "$WRAPPER" ]; then
    if [ ! -f "$WRAPPER" ]; then
        echo "ERROR: refusing to replace non-file path: $WRAPPER" >&2
        exit 1
    fi
    if ! grep -q "$MARKER" "$WRAPPER"; then
        echo "ERROR: refusing to replace existing file without the FreeUp Space marker:" >&2
        echo "$WRAPPER" >&2
        exit 1
    fi
fi

cat > "$WRAPPER" <<EOF
#!/bin/sh
# $MARKER
exec python3 "$CLI_SCRIPT" "\$@"
EOF

chmod 755 "$WRAPPER" || exit 1

echo "Installed FreeUp Space wrapper:"
echo "$WRAPPER"
echo
echo "Try:"
echo "  freeup-space --help"
echo "  freeup-space doctor"
echo

case ":$PATH:" in
    *":$INSTALL_DIR:"*)
        ;;
    *)
        echo "Add this directory to PATH if 'freeup-space' is not found:"
        echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
        ;;
esac

echo "No audit or cleanup command was run during install."
