#!/bin/bash
# Remove only the FreeUp Space CLI wrapper installed by install.sh.

set -u

INSTALL_DIR="$HOME/.local/bin"
WRAPPER="$INSTALL_DIR/freeup-space"
MARKER="FreeUp Space wrapper generated by install.sh"

if [ ! -e "$WRAPPER" ]; then
    echo "FreeUp Space wrapper is not installed at: $WRAPPER"
    exit 0
fi

if [ ! -f "$WRAPPER" ]; then
    echo "ERROR: refusing to remove non-file path: $WRAPPER" >&2
    exit 1
fi

if ! grep -q "$MARKER" "$WRAPPER"; then
    echo "ERROR: refusing to remove wrapper because it does not contain the expected marker." >&2
    echo "Path left untouched: $WRAPPER" >&2
    exit 1
fi

rm -f "$WRAPPER" || exit 1
echo "Removed FreeUp Space wrapper:"
echo "$WRAPPER"
echo "Reports, audit files, the repository, and user data were not removed."
